import React, { createContext, useContext, useState, ReactNode } from 'react';
export type Language = 'fr' |'ar';
interface LanguageContextProps {
    language: Language;
    setLanguage: (lang: Language) => void;
    toggleLanguage: () => void;
    translations: Record<Language, Record<string, string>>;

}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const translations = {
  fr: {
    welcome: 'Bienvenue',
    login: 'Connexion',
    logout: 'Déconnexion',
    error: 'Erreur',
    enterPhoneAndPassword: 'Veuillez saisir le numéro de téléphone et le mot de passe.',
    accessAccount: 'Accédez à votre compte',
    phonePlaceholder: 'Numéro de téléphone',
    passwordPlaceholder: 'Mot de passe',
    show: 'Afficher',
    hide: 'Cacher',
    or: 'ou',
    noAccount: 'Pas de compte ?',
    signup: 'Inscrivez-vous',
    forgotPassword: 'Mot de passe oublié ?',

    // Signup page translations
    signupTitle: "Inscription",
    signupSubtitle: "Créez votre compte",
    companyInfo: "Infos Entreprise",
    location: "Localisation",
    contact: "Contact",
    specialization: "Spécialisation",
    companyType: "Type d'entreprise",
    boutique: "Boutique",
    company: "Société",
    companyNamePlaceholder: "Nom de la boutique/société",
    managerNamePlaceholder: "Nom du gérant",
    socialReasonPlaceholder: "Raison sociale (optionnel)",
    addressPlaceholder: "Adresse",
    geolocation: "Géolocalisation",
    latitude: "Latitude",
    longitude: "Longitude",
    coveredZonePlaceholder: "Zone géographique couverte",
    emailPlaceholder: "Email",
    pieceTypes: "Types de pièces",
    new: "Neuf",
    used: "Occasion",
    specialBrandPlaceholder: "Marque spécialisée (optionnel)",
    specialModelPlaceholder: "Modèle spécialisé (optionnel)",
    confirmPasswordPlaceholder: "Confirmer le mot de passe",
    next: "Suivant",
    previous: "Précédent",
    alreadyHaveAccount: "Déjà un compte ? Connectez-vous",
    dashboardTitle: "Tableau de bord",
    notifications: "Notifications",
    help: "Aide",
    actions: "Actions",
    profile: "Profil",
    profileMessage: "Naviguer vers le profil",
    settings: "Paramètres",
    settingsMessage: "Naviguer vers les paramètres",
    logoutConfirm: "Déconnexion",
    logoutMessage: "Voulez-vous vraiment vous déconnecter ?",
    cancel: "Annuler",
    success: "Succès",
    acceptMessage: "Demande acceptée",
    refuseMessage: "Demande refusée",
    callError: "Impossible de passer l'appel",
    requestedBy: "Demandé par",
    requestDetails: "Détails de la demande",
    part: "Pièce",
    requester: "Demandeur",
    mobile: "Numéro",
    vinDetails: "Détails du véhicule (VIN)",
    make: "Marque",
    model: "Modèle",
    year: "Année",
    engine: "Moteur",
    transmission: "Transmission",
    accept: "Accepter",
    refuse: "Refuser",
    call: "Appeler",
    navigation: "Navigation",
    profileTitle: "Profil",
    profileSubtitle: "Gérez vos informations",
    selectZone: "Sélectionner une zone",
    selectBrand: "Sélectionner une marque",
    selectModel: "Sélectionner un modèle",
    edit: "Modifier",
    save: "Enregistrer",
    fillFields: "Veuillez remplir tous les champs requis correctement.",
    profileUpdated: "Profil mis à jour avec succès.",
    messages: "Messages",
    activeConversations: "Conversations actives",
    history: "Historique des demandes",
    
    // Dashboard specific
    dashboard: "Tableau de bord",
    hello: "Bonjour",
    viewProfile: "Voir le profil",
    editProfile: "Modifier le profil",
    allRequests: "Toutes les demandes",
    supplier: "Fournisseur",
    pending: "En attente",
    conversations: "Conversations",
    unread: "Non lus",
    completed: "Terminées",
    quickActions: "Actions rapides",
    viewAllRequests: "Voir toutes les demandes",
    noRequestsPending: "Aucune demande en attente",
    newRequestsWillAppear: "Les nouvelles demandes de pièces apparaîtront ici",
    
    // Messages page
    searchConversation: "Rechercher une conversation...",
    noConversationsFound: "Aucune conversation trouvée",
    noConversations: "Aucune conversation",
    tryModifyingSearch: "Essayez de modifier votre recherche",
    conversationsWillAppear: "Les conversations avec les clients apparaîtront ici",
    loadingMessages: "Chargement des messages...",
    
    // Parts requests page
    loadingRequests: "Chargement des demandes...",
    inProgress: "En cours",
    cancelled: "Annulées",
    searchRequest: "Rechercher une demande...",
    noRequestsFound: "Aucune demande trouvée",
    noRequests: "Aucune demande",
    requestsWillAppear: "Les demandes de pièces apparaîtront ici",
    
    // Common
    all: "Toutes",
    loading: "Chargement...",
    back: "Retour",
    
    // Parts request specific
    requestPart: "Demander une pièce détachée",
    selectPartType: "Sélectionner le type de pièce",
    selectVehicle: "Sélectionner le véhicule",
    selectCar: "Sélectionner une voiture",
    selectCarFirst: "Veuillez d'abord sélectionner une voiture",
    choosePart: "Choisir une pièce détachée",
    chooseCar: "Choisir une voiture",
    quantity: "Quantité",
    urgency: "Urgence",
    low: "Faible",
    medium: "Moyen",
    high: "Élevé",
    additionalNotes: "Notes supplémentaires",
    additionalInfo: "Informations supplémentaires...",
    createRequest: "Créer la demande",
    requestCreated: "Demande créée",
    requestCreatedMessage: "Votre demande de pièce a été créée avec succès. Les fournisseurs de pièces peuvent maintenant vous contacter.",
    sessionExpired: "Session expirée",
    sessionExpiredMessage: "Veuillez vous reconnecter pour continuer.",
    invalidRequest: "Demande invalide",
    invalidRequestMessage: "Veuillez vérifier vos informations et réessayer.",
    partNotFound: "Pièce non trouvée",
    partNotFoundMessage: "La pièce sélectionnée n'est plus disponible.",
    unableToCreateRequestMessage: "Impossible de créer la demande. Veuillez réessayer.",
    requestHelpText: "Après avoir soumis votre demande, les fournisseurs de pièces seront notifiés et pourront vous contacter via le système de messagerie avec des devis et la disponibilité.",
    noCarsAdded: "Aucune voiture trouvée",
    addCar: "Ajouter une voiture",
    loadingParts: "Chargement des pièces...",
    noPartsFound: "Aucune pièce trouvée",
    search: "Rechercher des pièces détachées...",
    inStock: "En stock",
    limited: "Limité",
    outOfStock: "Rupture de stock",
    
    // Dashboard specific content
    dashboardLoadingText: "Chargement du tableau de bord...",
    quickActions: "Actions rapides",
    viewAllRequestsButton: "Voir toutes\nles demandes",
    messagesButton: "Messages",
    pendingRequestsTitle: "Demandes en attente",
    seeAll: "Voir tout",
    loadingData: "Récupération des données en cours...",
    newRequestsWillAppearHere: "Les nouvelles demandes de pièces apparaîtront ici",
    requestDetails: "Détails de la demande",
    requesterLabel: "Demandeur:",
    vehicleLabel: "Véhicule:",
    licensePlate: "Immatriculation:",
    notesLabel: "Notes:",
    urgencyLabel: "Urgence:",
    dateLabel: "Date:",
    message: "Message",
    callAction: "Appeler",
    
    // Parts requests specific content
    partsRequestsTitle: "Demandes de pièces",
    searchByPartName: "Rechercher par nom de pièce, client ou véhicule...",
    noResultsFound: "Aucun résultat trouvé",
    tryModifyingSearch: "Essayez de modifier votre recherche",
    requestsWillAppearHere: "Les demandes de pièces apparaîtront ici",
    vehicleInfo: "Véhicule:",
    yearLabel: "Année:",
    fuelLabel: "Carburant:",
    engineLabel: "Moteur:",
    registrationLabel: "Immatriculation:",
    vinLabel: "VIN:",
    colorLabel: "Couleur:",
    mileageLabel: "Kilométrage:",
    km: "km",
    statusLabel: "État:",
    categoryLabel: "Catégorie:",
    clientNote: "Note du client:",
    garageInfo: "Informations garage:",
    serviceZone: "Zone de service:",
    services: "Services:",
    partPhotos: "Photo(s) de la pièce:",
    quantityLabel: "Quantité:",
    lastInteraction: "Dernière interaction:",
    numberNotAvailable: "Numéro non disponible",
    numberNotAvailableMessage: "Le numéro de téléphone du demandeur n'est pas disponible.",
    cannotOpenPhone: "Impossible d'ouvrir l'application téléphone",
    cannotMakeCall: "Impossible d'effectuer l'appel",
    urgent: "Urgent",
    normal: "Normal",
    justNow: "À l'instant",
    ago: "Il y a",
    min: "min",
    h: "h",
    d: "j",
    tapToClose: "Appuyez pour fermer",
    
    // Profile specific content
    personalInfo: "Informations personnelles",
    firstNamePlaceholder: "Prénom",
    lastNamePlaceholder: "Nom",
    phoneLabel: "Téléphone (8 chiffres)",
    companyLabel: "Nom de l'entreprise",
    vehicleBrands: "Marques spécialisées",
    vehicleModels: "Modèles spécialisés",
    compatible: "Compatible",
    disconnect: "Se déconnecter",
    logoutTitle: "Déconnexion",
    logoutConfirmMessage: "Voulez-vous vraiment vous déconnecter ?",
  },
  ar: {
    welcome: 'أهلا وسهلا',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    error: 'خطأ',
    enterPhoneAndPassword: 'يرجى إدخال رقم الهاتف وكلمة المرور.',
    accessAccount: 'ادخل إلى حسابك',
    phonePlaceholder: 'رقم الهاتف',
    passwordPlaceholder: 'كلمة المرور',
    show: 'إظهار',
    hide: 'إخفاء',
    or: 'أو',
    noAccount: 'ليس لديك حساب؟',
    signup: 'سجل الآن',
    forgotPassword: 'هل نسيت كلمة المرور؟',

    // Signup page translations
    signupTitle: "تسجيل حساب",
    signupSubtitle: "أنشئ حسابك",
    companyInfo: "معلومات الشركة",
    location: "الموقع",
    contact: "الاتصال",
    specialization: "التخصص",
    companyType: "نوع الشركة",
    boutique: "محل",
    company: "شركة",
    companyNamePlaceholder: "اسم المحل/الشركة",
    managerNamePlaceholder: "اسم المدير",
    socialReasonPlaceholder: "الاسم التجاري (اختياري)",
    addressPlaceholder: "العنوان",
    geolocation: "الموقع الجغرافي",
    latitude: "خط العرض",
    longitude: "خط الطول",
    coveredZonePlaceholder: "المنطقة الجغرافية المغطاة",
    emailPlaceholder: "البريد الإلكتروني",
    pieceTypes: "أنواع القطع",
    new: "جديد",
    used: "مستعمل",
    specialBrandPlaceholder: "العلامة المتخصصة (اختياري)",
    specialModelPlaceholder: "الموديل المتخصص (اختياري)",
    confirmPasswordPlaceholder: "تأكيد كلمة المرور",
    next: "التالي",
    previous: "السابق",
    alreadyHaveAccount: "لديك حساب؟ سجل الدخول",
    dashboardTitle: "لوحة التحكم",
    notifications: "الإشعارات",
    help: "مساعدة",
    actions: "إجراءات",
    profile: "الملف الشخصي",
    profileMessage: "الانتقال إلى الملف الشخصي",
    settings: "الإعدادات",
    settingsMessage: "الانتقال إلى الإعدادات",
    logoutConfirm: "تسجيل الخروج",
    logoutMessage: "هل تريد تسجيل الخروج؟",
    cancel: "إلغاء",
    success: "نجاح",
    acceptMessage: "تم قبول الطلب",
    refuseMessage: "تم رفض الطلب",
    callError: "تعذر إجراء المكالمة",
    requestedBy: "طلب من قبل",
    requestDetails: "تفاصيل الطلب",
    part: "القطعة",
    requester: "الطالب",
    mobile: "رقم الهاتف",
    vinDetails: "تفاصيل السيارة (VIN)",
    make: "الماركة",
    model: "الموديل",
    year: "السنة",
    engine: "المحرك",
    transmission: "ناقل الحركة",
    accept: "قبول",
    refuse: "رفض",
    call: "اتصال",
    navigation: "التنقل",
    profileTitle: "الملف الشخصي",
    profileSubtitle: "إدارة معلوماتك",
    selectZone: "اختر منطقة",
    selectBrand: "اختر ماركة",
    selectModel: "اختر موديل",
    edit: "تعديل",
    save: "حفظ",
    fillFields: "يرجى ملء جميع الحقول المطلوبة بشكل صحيح.",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح.",
    messages: "الرسائل",
    activeConversations: "المحادثات النشطة",
    history: "سجل الطلبات",
    
    // Dashboard specific
    dashboard: "لوحة القيادة",
    hello: "مرحباً",
    viewProfile: "عرض الملف الشخصي",
    editProfile: "تعديل الملف الشخصي",
    allRequests: "جميع الطلبات",
    supplier: "مورد",
    pending: "في الانتظار",
    conversations: "المحادثات",
    unread: "غير مقروء",
    completed: "مكتملة",
    quickActions: "إجراءات سريعة",
    viewAllRequests: "عرض جميع الطلبات",
    noRequestsPending: "لا توجد طلبات معلقة",
    newRequestsWillAppear: "ستظهر طلبات القطع الجديدة هنا",
    
    // Messages page
    searchConversation: "البحث في المحادثات...",
    noConversationsFound: "لم يتم العثور على محادثات",
    noConversations: "لا توجد محادثات",
    tryModifyingSearch: "جرب تعديل البحث",
    conversationsWillAppear: "ستظهر المحادثات مع العملاء هنا",
    loadingMessages: "تحميل الرسائل...",
    
    // Parts requests page
    loadingRequests: "تحميل الطلبات...",
    inProgress: "قيد التنفيذ",
    cancelled: "ملغاة",
    searchRequest: "البحث في الطلبات...",
    noRequestsFound: "لم يتم العثور على طلبات",
    noRequests: "لا توجد طلبات",
    requestsWillAppear: "ستظهر طلبات القطع هنا",
    
    // Common
    all: "الكل",
    loading: "تحميل...",
    back: "رجوع",
    
    // Parts request specific
    requestPart: "طلب قطعة غيار",
    selectPartType: "اختيار نوع القطعة",
    selectVehicle: "اختيار المركبة",
    selectCar: "اختيار سيارة",
    selectCarFirst: "يرجى اختيار سيارة أولاً",
    choosePart: "اختيار قطعة غيار",
    chooseCar: "اختيار سيارة",
    quantity: "الكمية",
    urgency: "الأولوية",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    additionalNotes: "ملاحظات إضافية",
    additionalInfo: "معلومات إضافية...",
    createRequest: "إنشاء الطلب",
    requestCreated: "تم إنشاء الطلب",
    requestCreatedMessage: "تم إنشاء طلب القطعة بنجاح. يمكن لموردي القطع الآن الاتصال بك.",
    sessionExpired: "انتهت الجلسة",
    sessionExpiredMessage: "يرجى تسجيل الدخول مرة أخرى للمتابعة.",
    invalidRequest: "طلب غير صحيح",
    invalidRequestMessage: "يرجى التحقق من المعلومات والمحاولة مرة أخرى.",
    partNotFound: "القطعة غير موجودة",
    partNotFoundMessage: "القطعة المحددة لم تعد متوفرة.",
    unableToCreateRequestMessage: "تعذر إنشاء الطلب. يرجى المحاولة مرة أخرى.",
    requestHelpText: "بعد تقديم طلبك، سيتم إشعار موردي القطع ويمكنهم الاتصال بك عبر نظام المراسلة مع عروض الأسعار والتوفر.",
    noCarsAdded: "لم يتم العثور على سيارات",
    addCar: "إضافة سيارة",
    loadingParts: "تحميل القطع...",
    noPartsFound: "لم يتم العثور على قطع",
    search: "البحث عن قطع الغيار...",
    inStock: "متوفر في المخزون",
    limited: "محدود",
    outOfStock: "نفد من المخزون",
    
    // Dashboard specific content
    dashboardLoadingText: "تحميل لوحة القيادة...",
    quickActions: "إجراءات سريعة",
    viewAllRequestsButton: "عرض جميع\nالطلبات",
    messagesButton: "الرسائل",
    pendingRequestsTitle: "طلبات في الانتظار",
    seeAll: "عرض الكل",
    loadingData: "جاري استرداد البيانات...",
    newRequestsWillAppearHere: "ستظهر طلبات القطع الجديدة هنا",
    requestDetails: "تفاصيل الطلب",
    requesterLabel: "الطالب:",
    vehicleLabel: "المركبة:",
    licensePlate: "لوحة التسجيل:",
    notesLabel: "الملاحظات:",
    urgencyLabel: "الأولوية:",
    dateLabel: "التاريخ:",
    message: "رسالة",
    callAction: "اتصال",
    
    // Parts requests specific content
    partsRequestsTitle: "طلبات القطع",
    searchByPartName: "البحث بواسطة اسم القطعة أو العميل أو المركبة...",
    noResultsFound: "لم يتم العثور على نتائج",
    tryModifyingSearch: "جرب تعديل البحث",
    requestsWillAppearHere: "ستظهر طلبات القطع هنا",
    vehicleInfo: "المركبة:",
    yearLabel: "السنة:",
    fuelLabel: "الوقود:",
    engineLabel: "المحرك:",
    registrationLabel: "لوحة التسجيل:",
    vinLabel: "رقم الهيكل:",
    colorLabel: "اللون:",
    mileageLabel: "المسافة المقطوعة:",
    km: "كم",
    statusLabel: "الحالة:",
    categoryLabel: "الفئة:",
    clientNote: "ملاحظة العميل:",
    garageInfo: "معلومات الورشة:",
    serviceZone: "منطقة الخدمة:",
    services: "الخدمات:",
    partPhotos: "صورة/صور القطعة:",
    quantityLabel: "الكمية:",
    lastInteraction: "آخر تفاعل:",
    numberNotAvailable: "الرقم غير متوفر",
    numberNotAvailableMessage: "رقم هاتف الطالب غير متوفر.",
    cannotOpenPhone: "تعذر فتح تطبيق الهاتف",
    cannotMakeCall: "تعذر إجراء المكالمة",
    urgent: "عاجل",
    normal: "عادي",
    justNow: "الآن",
    ago: "منذ",
    min: "دقيقة",
    h: "ساعة",
    d: "يوم",
    tapToClose: "اضغط للإغلاق",
    
    // Profile specific content
    personalInfo: "المعلومات الشخصية",
    firstNamePlaceholder: "الاسم الأول",
    lastNamePlaceholder: "اسم العائلة",
    phoneLabel: "الهاتف (8 أرقام)",
    companyLabel: "اسم الشركة",
    vehicleBrands: "العلامات المتخصصة",
    vehicleModels: "الموديلات المتخصصة",
    compatible: "متوافق",
    disconnect: "تسجيل الخروج",
    logoutTitle: "تسجيل الخروج",
    logoutConfirmMessage: "هل تريد تسجيل الخروج؟",
  }
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');
  const toggleLanguage = () => setLanguage(language === 'fr' ? 'ar' : 'fr');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}